apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kg-platform-local
  namespace: kg-platform
spec:
  rules:
    - http:
        paths:
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
